using System;

namespace Quaver.Shared.Input.Global;

[Flags]
public enum GlobalKeybindActions : ulong
{
    Screenshot,
    OpenOptions,
    ToggleFullscreen,
    TogglePause,
    CycleFpsLimiter,
    ToggleOnlineHub,
    ReloadSkin,
    Back,
    IncreaseRate,
    TogglePitch,
    RemoveMods,
    ToggleMirror,
    IncreaseScrollSpeed,
    IncreaseOffset,
    GameplayPause,
    GameplayPauseUp,
    GameplayToggleScoreboard,
    GameplayToggleOverlay,
    GameplayRetry,
    GameplayQuickExit,
    GameplaySkipIntro,
    GameplayTogglePlaytestAutoplay,
    ResetOffset,
    NavigateRight,
    NavigateUp,
    NavigateSelect,
    ResultsTab,
    DialogConfirm,
    DialogCancel,

    BaseActionMask = (1 << 16) - 1,

    Reverse = 1ul << 60,
    Visual = 1ul << 61,
    Local = 1ul << 62,
    Small = 1ul << 63,

    DecreaseRate = IncreaseRate | Reverse,
    IncreaseRateSmall = IncreaseRate | Small,
    DecreaseRateSmall = IncreaseRateSmall | Reverse,
    DecreaseScrollSpeed = IncreaseScrollSpeed | Reverse,
    IncreaseLocalScrollSpeed = IncreaseScrollSpeed | Local,
    DecreaseLocalScrollSpeed = DecreaseScrollSpeed | Local,
    IncreaseScrollSpeedSmall = IncreaseScrollSpeed | Small,
    DecreaseScrollSpeedSmall = IncreaseScrollSpeedSmall | Reverse,
    IncreaseLocalScrollSpeedSmall = IncreaseScrollSpeedSmall | Local,
    DecreaseLocalScrollSpeedSmall = IncreaseLocalScrollSpeedSmall | Reverse,
    DecreaseOffset = IncreaseOffset | Reverse,
    IncreaseOffsetSmall = IncreaseOffset | Small,
    DecreaseOffsetSmall = DecreaseOffset | Small,
    IncreaseVisualOffset = IncreaseOffset | Visual,
    DecreaseVisualOffset = IncreaseVisualOffset | Reverse,
    IncreaseVisualOffsetSmall = IncreaseVisualOffset | Small,
    DecreaseVisualOffsetSmall = IncreaseVisualOffsetSmall | Reverse,
    ResetVisualOffset = ResetOffset | Visual,
    NavigateDown = NavigateUp | Reverse,
    NavigateLeft = NavigateRight | Reverse,
    GameplayPauseDown = GameplayPauseUp | Reverse,
}
